import Head from "next/head";
import LandingBot from "../components/LandingBot";
import LandingMid from "../components/LandingMid";
import LandingTop from "../components/LandingTop";
import Preview from "../components/Preview";
import Content from "../components/Content";
import Slider from "../components/Slider";
import sliders from "../sliders";
// import Cart from "../components/Cart";
// import carts from "../carts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Starbucks Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fannn  nnm, mvicon.ico" />
      </Head>
      <main>
        <div className="space-y-5">
          <LandingTop />
          <LandingMid />
          <LandingBot />
        </div>
        <div className="py-9 bg-[#efefef] space-y-5">
          <Content
            contentImg="https://bit.ly/3MKqK33"
            contentH1="Starbucks® Rewards 🌟 "
            contentP1="Summer season is here and so is our handcrafted Strawberry Acai Starbucks Refresha® Drink."
            contentP2="Order on the Starbucks® UK App for a speedy pick up. "
            contentButtons="Order now"
          />
          <Content
            contentImg="https://bit.ly/3xQyLPN"
            contentH1="Starbucks® Delivers 🌟 "
            contentP1="You're one tap away from trying the Iced Brown Sugar Oat Shaken Espresso."
            contentP2="Get it delivered straight to your door with Starbucks® Delivers."
            contentButtons="Order now"
          />
        </div>
        <Preview />
        <h1 className=" bg-[#efefef] flex justify-center text-5xl font-britney pt-14">
          Choose Your Coffee
        </h1>
        <div className="slider flex bg-[#efefef] py-14 px-3 space-x-3 ">
          {sliders.map(({ sliderH1, sliderImg, sliderPrice }, index) => (
            <Slider
              key={index}
              sliderImg={sliderImg}
              sliderH1={sliderH1}
              sliderPrice={sliderPrice}
            />
          ))}
        </div>
        {/* <div>
          {carts.map(({ cartH1, cartImg, cartPrice }, index) => (
            <rt
              key={index}
              cartImg={cartImg}
              cartH1={cartH1}
              cartPrice={cartPrice}
            />
          ))}
        </div> */}
      </main>
    </div>
  );
}
